% plot_time_series.m

% Plot scaled cumulants as a function of time, based on data generated by
% data_p_dga.m

% Matthew Gerry, June 2024

% Specify name of data file, calculate cumulants
% filename = "RWdata_lowbias_24-06-07_1147";
filename = "RWdata_nobias_24-06-07_1547";
[C1,C2,C3,C4] = stats_p_dga(filename);

% Load parameter values from data file
load(strcat("../", filename, ".mat"), "dt","tmax","numsites","set_size","dp","tau","ga_av","ddga","b","site0")

% Re-define some of the parameter-dependent variables
time = 0:dt:tmax; % Time
site_list = -floor(numsites/2):floor(numsites/2); % List of site indices
dga_list = 0:ddga:2*ga_av; % List of dga values
p_list = 0:dp:1; % List of p values

%%
% Plot cumulant as a function of time for many realizations of the same parameters
% At a few choices of p value, specific choice of dga
figure;
p_indices = [2,6,9];

for ii=1:length(p_indices)
    p = p_list(p_indices(ii));
    subplot(1, length(p_indices), ii); hold on; box on
    for jj=1:set_size
        plot(time, reshape(C2(2, p_indices(ii), jj, :),[1,length(time)]))
    end
    xlim([0,time(end)])
    xlabel("$t$",interpreter="latex")
    ylabel("$C_2$",interpreter="latex")
    title(strcat("$p=",num2str(p),"$"),interpreter="latex")
    set(gca, fontsize=14)
    hold off
end

%%
% Plot cumulant as a function of time for many realizations of the same parameters
% At a few choices of dga value, specific choice of p
figure;
dga_indices = [2,6,9];

for ii=1:length(dga_indices)
    dga = dga_list(dga_indices(ii));
    subplot(1, length(dga_indices), ii); hold on; box on
    for jj=1:set_size
        plot(time, reshape(C2(dga_indices(ii), 6, jj, :),[1,length(time)]))
    end
    xlim([0,time(end)])
    ylim([0, 4])
    xlabel("$t$",interpreter="latex")
    ylabel("$C_2$",interpreter="latex")
    title(strcat("$\Delta\gamma=",num2str(dga),"$"),interpreter="latex")
    set(gca, fontsize=14)
    hold off
end

%% Timescale analysis, just choose p=0.5, dga=1

figure; hold on; box on
semilogx(time, reshape(C2(6, 6, 1, :),[1,length(time)]))

hold off
